// This file was autogenerated by ../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../ray/keys.js', ['ray.Key', 'ray.Keys'], ['goog.events', 'goog.events.KeyHandler']);
goog.addDependency('../../../ray/ray.js', ['ray'], ['ray.Keys']);
